// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_credential.sql

package webauthn

import (
	"context"
)

const getCredential = `-- name: GetCredential :one
SELECT id, principal_id, sign_count, uv_initialized, transports, backup_state, attestation_object, attestation_client_data_json, rp_id, current_login_challenge
  FROM credential
 WHERE id = $1
`

func (q *Queries) GetCredential(ctx context.Context, id []byte) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredential, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.SignCount,
		&i.UvInitialized,
		&i.Transports,
		&i.BackupState,
		&i.AttestationObject,
		&i.AttestationClientDataJson,
		&i.RpID,
		&i.CurrentLoginChallenge,
	)
	return i, err
}
