// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login.sql

package webauthn

import (
	"context"
)

const login = `-- name: Login :execrows
WITH consumed AS (
  UPDATE credential
     SET sign_count = $3, backup_state = $4, uv_initialized = $5, current_login_challenge = NULL
   WHERE credential.id = $1 AND credential.current_login_challenge = $2
  RETURNING principal_id
)
UPDATE principal
   SET grant_hash = $6, last_authenticated_date = $7
  FROM consumed
 WHERE principal.id = consumed.principal_id
`

type LoginParams struct {
	ID                    []byte
	CurrentLoginChallenge []byte
	SignCount             int64
	BackupState           bool
	UvInitialized         bool
	GrantHash             []byte
	LastAuthenticatedDate int64
}

func (q *Queries) Login(ctx context.Context, arg LoginParams) (int64, error) {
	result, err := q.db.Exec(ctx, login,
		arg.ID,
		arg.CurrentLoginChallenge,
		arg.SignCount,
		arg.BackupState,
		arg.UvInitialized,
		arg.GrantHash,
		arg.LastAuthenticatedDate,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
