// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package webauthn

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Credential struct {
	ID                        []byte
	PrincipalID               pgtype.UUID
	SignCount                 int64
	UvInitialized             bool
	Transports                []string
	BackupState               bool
	AttestationObject         []byte
	AttestationClientDataJson []byte
	RpID                      pgtype.Text
	CurrentLoginChallenge     []byte
}
