// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: register.sql

package webauthn

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const register = `-- name: Register :exec
WITH inserted AS (
  INSERT INTO principal (id, name, display_name, creation_date, last_authenticated_date, grant_hash)
  VALUES ($1, $2, $3, $4, $5, $6)
  RETURNING id
)
INSERT INTO credential (id, principal_id, sign_count, uv_initialized, backup_state,
                        attestation_object, attestation_client_data_json, transports, rp_id)
SELECT $7, inserted.id, $8, $9, $10, $11, $12, $13, $14
  FROM inserted
`

type RegisterParams struct {
	ID                        pgtype.UUID
	Name                      string
	DisplayName               string
	CreationDate              int64
	LastAuthenticatedDate     int64
	GrantHash                 []byte
	ID_2                      []byte
	SignCount                 int64
	UvInitialized             bool
	BackupState               bool
	AttestationObject         []byte
	AttestationClientDataJson []byte
	Transports                []string
	RpID                      pgtype.Text
}

func (q *Queries) Register(ctx context.Context, arg RegisterParams) error {
	_, err := q.db.Exec(ctx, register,
		arg.ID,
		arg.Name,
		arg.DisplayName,
		arg.CreationDate,
		arg.LastAuthenticatedDate,
		arg.GrantHash,
		arg.ID_2,
		arg.SignCount,
		arg.UvInitialized,
		arg.BackupState,
		arg.AttestationObject,
		arg.AttestationClientDataJson,
		arg.Transports,
		arg.RpID,
	)
	return err
}
