// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: set_login_challenge.sql

package webauthn

import (
	"context"
)

const setLoginChallenge = `-- name: SetLoginChallenge :execrows
UPDATE credential SET current_login_challenge = $2 WHERE id = $1
`

type SetLoginChallengeParams struct {
	ID                    []byte
	CurrentLoginChallenge []byte
}

func (q *Queries) SetLoginChallenge(ctx context.Context, arg SetLoginChallengeParams) (int64, error) {
	result, err := q.db.Exec(ctx, setLoginChallenge, arg.ID, arg.CurrentLoginChallenge)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
